#!/usr/bin/env python3
# about logging xscreensaver
# https://gemini.google.com/share/aad943314f02
#

import subprocess
import os
import random
import time
import re
import sys
#import glob
import json
from time import sleep
import argparse
import sqlite3
import socket
import atexit


mpv_error={
 0 : "Success"
,1 :"Event queue full"
,2 :"Memory allocation failed"
,3 :"mpv core not initialized"
,4 :"Invalid or unsupported parameter value"
,5 :"Option doesn't exist"
,6 :"Unsupported option format"
,7 :"Option parsing failed"
,8 :"Property doesn't exist"
,9 :"Unsupported property format"
,10:"Property unavailable (subsystem inactive)"
,11:"Error setting or getting property"
,12:"General command error"
,13:"Generic loading error"
,14:"Audio output initialization failed"
,15:"Video output initialization failed"
,16:"No audio or video data to play"
,17:"Unknown file format"
,18:"Unsupported system requirements"
,19:"Function not implemented"
}
# from icecream import ic
# ic.configureOutput(includeContext=True)

parser = argparse.ArgumentParser(
	prog='ExploreOrgScreenSaver',
	description='A xscreensaver hack to play streams as in the screensaver\nread the readme.md for more info.\n',
	epilog='Enjoy'
)

parser.add_argument('-t', '--show-time',default=20.0,type=int,nargs='?',help="time in seconds a stream is shown")
parser.add_argument('-w', '--window-id', type=str, nargs='?', help="root window id passed by the xscreensaver")
parser.add_argument('-m', '--mode', type=str, nargs='?', help='How to scale a stream "original","stretch" or "zoom"')
parser.add_argument('-o', '--only-tested', action='store_true', help="Don't try to show untested streams")
parser.add_argument('-s', '--socket', action='store_true', help="Use mpv as sever on a socket")

args = parser.parse_args()

CONFIG_DIR = os.path.expanduser("~/.config/stream_catcher/")
EXPLORE_ORG_DB = CONFIG_DIR + 'explore.org.db'
#COOKIES_FILE=CONFIG_DIR+ 'cookies.txt'
#PATIENTS_SECS = .4
#CLIP_LENGTH   = 20.0
MAX_PICK = 1200

STORED_GOOD = 0
STORED_BAD  = 1
NOT_STORED  = 2
NEED_LOOKUP = 3

def xscreensaver_window_options():
	if not 'XSCREENSAVER_WINDOW' in os.environ:
		return []
	xscreensaver_window=os.environ['XSCREENSAVER_WINDOW']
	return [
	"-no-audio"
	,"-quiet"
	,"-hwdec=no"
	#,"-really-quiet"
	,"--fullscreen"
	#--stop-screensaver=<yes|no|always>
	,"--stop-screensaver=always"
	,'--wid='+str(xscreensaver_window)
	]
	
def screen_mode_options():
	if not args.mode:
		return []
	if args.mode == 'original':
		return[]
	if args.mode == 'stretch':
		return ["--keepaspect=no"]
	if args.mode == 'zoom':
		return ["--video-zoom=1", "--panscan=1.0"]
	return []

class MpvOutput(dict):
	# (+) Video --vid=1 (h264 1920x1080 30.000fps)
    # (+) Audio --aid=1 (aac 2ch 44100Hz)
    #AO: [pipewire] 44100Hz stereo 2ch floatp
    #VO: [gpu] 1920x1080 yuv420p

	def __init__(S,txt):
		dict.__init__(S)
		val1 = val2 = False
		lines=txt.split('\n')
		for line in lines:
			if not val1:
				match = re.findall(r'Video [^(]+\((\S+) (\d\d\d*)x(\d\d\d*) ([\d.]*)',line)
				if match:
					val1 = True
					item = match[0]
					S['video_codec']=item[0]
					S['scrw']= int(item[1])
					S['scrh']= int(item[2])
					S['fps'] = int(item[3].replace('.',''))
			if not val2:
				match = re.findall(r'Audio [^(]+\((\S+) (\d+)ch (\d+)Hz',line)
				if match:
					val2 = True
					item = match[0]
					S['audio_codec']    = item[0]
					S['audio_channels'] = int(item[1])
					S['sample_rate']    = int(item[2])
			S['valid'] = val1 and val2
			if S['valid']:
				S.show()
				return
		
	def show(S):
		print(json.dumps(S,indent=4))

class SocketMpv:
	# https://mpv.io/manual/stable/#json-ipc
	def __init__(S,clip_length, patients_secs = .3):
		S.clip_length   = clip_length
		S.options = ["mpv"]
		S.options += xscreensaver_window_options()
		S.options += screen_mode_options()
		
		sock = int((time.time() * 1000) % 1000)
		S.socket_path = '/tmp/mpv-socket-'+ str(sock)
		print(f'{S.socket_path=}')
		S.options += ['--input-ipc-server='+S.socket_path,'--idle']
		S.server_proc = subprocess.Popen(
			S.options + ["data/intro.mp4"],
			stdout=subprocess.PIPE,stderr=subprocess.STDOUT
		)
		time.sleep(.5)
		S.count_down = S.clip_length
		S.dt_check = .3
		S.request_id = 0
	
	def socket(S):
		return True
	
	def send_command(S, *args):
		"""Formats and sends a JSON command to the mpv socket."""
		if not os.path.exists(S.socket_path):
			print(f"Error: Socket {S.socket_path} not found. Is mpv running?")
			return None
		
		# Build the JSON payload
		S.request_id += 1
		payload = {"command": list(args), "request_id": S.request_id }
		
		# Connect to the Unix Domain Socket
		with socket.socket(socket.AF_UNIX, socket.SOCK_STREAM) as client:
			client.connect(S.socket_path)
			client.sendall((json.dumps(payload) + '\n').encode('utf-8'))
			
			# Receive response (mpv sends a JSON response for every command)
			response = client.recv(4096)
			ret_str=response.decode('utf-8').strip()
			print(f'response utf-8 "{ret_str}"')
			return ret_str
		
	def clip_show(S,url):
		running = False
		while S.count_down > 0.0:
			res = S.send_command("get_property", "time-pos" )
			time.sleep(S.dt_check)
			S.count_down -= S.dt_check
			resdict = json.loads(res)
			if resdict["error"] == "success":
				running = True
				continue
			if ["error"] == "property unavailable":
			
			print (json.dumps(resdict,indent=4))
			S.send_command('loadfile', url, 'replace')
		return False,'testing'
		
class ExploreOrgStream:
	url_base = "https://outbound-production.explore.org/stream-production-"
	url_tail = "/.m3u8"

	def __init__(S,displayer,streamdb,max_pick):
		S.displayer  = displayer
		S.streamdb   = streamdb
		S.max_pick   = max_pick
		#S.temp_list_current = len(ExploreOrgStream.temp_list)
		
	def url_str(S):
		return S.url_base+ str(S.pick) + S.url_tail
	
	def pick_a_nice_stream(S):
		#print ()
		while True:
			S.pick = random.randint(0,S.max_pick) + 1
			#S.pick = S.pick_from_list()
			print (f'[{S.pick:4} ',end='')
			if S.streamdb.is_bad_boy(S.pick) == STORED_BAD:
				print (f'BBOY] ',end='')
				continue
			#print(f'{S.pick=}')
			S.url = S.url_str()
			S.url_status = S.streamdb.url_status_lookup(S.url)
			if S.url_status == STORED_BAD : # tested and bad, throw the dice agian
				print(f'SBAD] ',end='')
				continue
			if args.only_tested and S.url_status == NOT_STORED:
				print(f'NEW ] ',end='')
				continue
			if S.url_status == NOT_STORED:
				print (f'NEW ] ',end='')
				
			else:
				print (f'GOOD] ',end='')
			return # working on merging an old list
	
	def run(S):
		
		while True:
			S.pick_a_nice_stream()
			#print(f'run shows "{S.url}" with {S.url_status=}')
			ok,data = S.displayer.clip_show(S.url)
			if ok:
				if S.url_status == STORED_GOOD: # Was ok and still ok no action
					continue
				# new working stream put it in the db
				S.streamdb.store_good_status(S.url,data)
				continue
			else:
				if S.url_status == NOT_STORED:
					S.streamdb.store_bad_status(S.url)
					nap = random.random()*7
					time.sleep(nap)
					
class MpvPlayer:
	
	def __init__(S,clip_length, patients_secs = .3):
		print(f'MpvPlayer({clip_length=}, {patients_secs})')
		S.patients_secs = patients_secs
		S.clip_length   = clip_length
		S.options = ["mpv"]
		S.options += xscreensaver_window_options()
		S.options += screen_mode_options()
		
		#print (f'{S.options=}')
	
	def socket(S):
		return False
		
	def clip_show(S,url:str):
		"""
		run mpv with the given url
		:param url: an explore.org m3u8 url
		:type url: str
		:return: True is stream was displayed with success
		:rtype: bool
		"""
		command = ' '.join(S.options + [url] )
		print(f'command : {command}',end=' ')
		mpv_proc = subprocess.Popen(S.options + [url],stdout=subprocess.PIPE,stderr=subprocess.PIPE,text=True)
		_patience = 0.0
		_tik = S.patients_secs / 200
		while _patience < S.patients_secs:
			time.sleep(_tik)
			_patience += _tik
			if mpv_proc.poll():
				print(f'{mpv_proc.returncode} after {_patience} sec.')
		
		_count_down = S.clip_length - S.patients_secs
		while _count_down > 0:
			check = mpv_proc.poll()
			if check:
				# print(f'FAILED at {_count_down} error {check} code {mpv_proc.returncode}')
				S.precent_error(mpv_proc.stderr.read())
				mpv_proc.terminate()
				return False,'Bad'
			time.sleep(S.patients_secs)
			_count_down -= S.patients_secs
			
		mpv_proc.terminate()
		
		stdout_txt = mpv_proc.stdout.read()
		#print(f'clip_show("{url}")-> True,>>>>{stdout_txt}<<<<')
		print ("Success")
		return True,stdout_txt
	
	def precent_error(S,e_txt):
		if 'rror 403' in e_txt:
			print ('Error 403: Forbidden')
			return
		for line in e_txt.split('\n'):
			print(f'\t{line}')
			
		error_txt = e_txt.split('\n')
		

class ExploreOrgDb:

	table = """
        CREATE TABLE IF NOT EXISTS streams (
            url    TEXT PRIMARY KEY,
            good   INTEGER DEFAULT 1,
            width  INTEGER DEFAULT 0,
            height INTEGER DEFAULT 0,
            time   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        );"""
	
	def __init__(S):
		S.createdb_if_needed()
		S.bad_boys_set = set()
		S.num_reg = re.compile(r'-(\d+)/\.')
		S.old_bad_boys()
		
	def store_good_status(S,url:str,data:str)->None:
		"""
		store a good status for a given url
		:param url: a tested url that worked with mpv
		:type url: text
		:param data: output of mpv piped stdout
		:type data: str
		:return: None
		:rtype: None
		"""
		si = MpvOutput(data)
		if not si['valid']:
			print (f'No valid mpv data')
			si.show()
		
		try:
			with sqlite3.connect(EXPLORE_ORG_DB) as con:
				cur = con.cursor()
				try:
					
					cur.execute("INSERT INTO streams VALUES (:url,:good,:width,:height,:time)",
				            {'url':url
					            ,'good':True
					            ,'width':si['scrw']
					            ,'height':si['scrh']
					            ,'time':time.time()})
				except KeyError as e :
					si.show()
					print(e)
					raise
				con.commit()
		except sqlite3.IntegrityError as e:
			if "UNIQUE constraint failed" in str(e):
				print("Skipping: This URL is already in the database.")
			else:
				raise e

	def store_bad_status(S,url:str)->None:
		"""
		store a bad status for a given url
		:param url: a tested url that not worked with mpv
		:type url: text
		:return: None
		:rtype: None
		"""
		
		with sqlite3.connect(EXPLORE_ORG_DB) as con:
			cur = con.cursor()
			try:
				cur.execute("INSERT INTO streams VALUES (:url,:good,:width,:height,:time)"
				            ,{'url':url,'good':False,'width':0,'height':0,'time':time.time()})
				con.commit()
			except sqlite3.IntegrityError as e:
				if "UNIQUE constraint failed" in str(e):
					print("Skipping: This URL is already in the database.")
				else:
					raise e

	def is_bad_boy(S,id):
		if id in S.bad_boys_set:
			return STORED_BAD
		return NEED_LOOKUP
	
	def url_status_lookup(S,url:str)->int:
		"""
		Look the url up in the database store result in S.lookup
		:param url: url to look up
		:type url: str
		:return: 0 = ok, 1 = bad, 2 = not checked not in the database jet
		:rtype: int
		"""
		
		with sqlite3.connect(EXPLORE_ORG_DB) as conn:
			cursor = conn.cursor()
			cursor.execute("SELECT * FROM streams WHERE url=?", (url,))
			row = cursor.fetchone()
		if not row:
			return NOT_STORED
		if row[1] == True: # the "good" field
			return STORED_GOOD
		return STORED_BAD

	def old_bad_boys(S):
		#reg = re.compile(r'-(\d+)/\.')
		with sqlite3.connect(EXPLORE_ORG_DB) as con:
			cursor = con.cursor()
			try:
				cursor.execute("SELECT url FROM streams WHERE good=?", (0,))
				rows = cursor.fetchall()
				#print(rows)
			except sqlite3.OperationalError as e:
				print(e)
				
		for url_tuple in rows:
			url = url_tuple[0]
			#print(f'{url=}')
			match = S.num_reg.findall(url)
			if match:
				id = int(match[0])
				S.bad_boys_set.add(id)
		#print(S.bad_boys_set)
		
	def createdb_if_needed(S):
		if not os.path.isdir(CONFIG_DIR):
			try:
				os.mkdir(CONFIG_DIR)
			except OSError as e:
				print(f'Could not make dir "{CONFIG_DIR}".')
				print(e)
				exit(e.errno)
		try:
			con = sqlite3.connect(EXPLORE_ORG_DB)
			print(f'Opened "{EXPLORE_ORG_DB}" SQLite database\nwith version {sqlite3.sqlite_version} successfully.')
		except sqlite3.OperationalError as e:
			print(f'"Failed to open "{EXPLORE_ORG_DB}"')
			print(e)
			exit(1)
		cur = con.cursor()
		cur.execute(ExploreOrgDb.table)
		con.close()


def main():
	global CONFIG_DIR
	#print (sys.argv)
	if args.socket:
		clip_displayer=SocketMpv(args.show_time)
	else:
		clip_displayer=MpvPlayer(args.show_time)
	url_db = ExploreOrgDb()
	
	saver = ExploreOrgStream(clip_displayer,url_db,MAX_PICK)
	saver.run()
	
def socket_tester():
	mpv_sock=SocketMpv()
	mpv_sock.send_command("show-text", "Hello from Python!", "10000")
	time.sleep(20)
	print(f'bye from Socket tester')
	
if __name__ == '__main__':
	# socket_tester()
	# exit(0)
	print(f'ExploreOrgScreenSaver pid({os.getpid()})')
	try:
		main()
	except KeyboardInterrupt as e:
		print(e)
		print("\nScreensaver halted.")
		sys.exit(0)
		
