#!/usr/bin/env python3
# lives as /usr/libexec/xscreensaver/StreamScreenSaver

import subprocess
import os
import random
import time
import psutil
import sys
import glob
import json
from time import sleep
import argparse

parser = argparse.ArgumentParser(
	prog='StreamScreenSaver',
	description='A xscreensaver hack to play streams as in the screensaver\nread the readme.md for more info.\n',
	epilog='Enjoy'
)

parser.add_argument('-t', '--show-time',type=int,nargs='?',help="time in seconds a stream is shown")
parser.add_argument('-w', '--window-id', type=str, nargs='?', help="root window id passed by the xscreensaver")
parser.add_argument('-m', '--mode', type=str, nargs='?', help='How to scale a stream "original","stretch" or "zoom"')

args = parser.parse_args()

BROWSERS = ["chrome", "firefox", "brave", "opera", "chromium"]
CONFIG_DIR=os.path.expanduser("~/.config/stream_catcher/")
COOKIES_FILE=CONFIG_DIR+ 'cookies.txt'
STREAMS = []
LEN_STREAMS = 0

# Parameter candidates
SHOW_TIME_SECS = 12  # Time to show the stream in seconds
START_TIMEOUT_SECS = 15  # Time to wait for a stream to start

XSCREENSAVER_WINDOW=None
if 'XSCREENSAVER_WINDOW' in os.environ:
	XSCREENSAVER_WINDOW=os.environ['XSCREENSAVER_WINDOW']
	print(f'{XSCREENSAVER_WINDOW=}')

ACTIVE_STREAM = None
YOUTUBE_IS_NICE = True

def read_streams():
	"""
	read the stream url's from ~/.config/stream_catcher/*.json
	a list of dict with the field 'url' in it
	:return: appends to global STREAMS
	:rtype: None
	"""
	global STREAMS,LEN_STREAMS
	#print(CONFIG_DIR+'*.json')
	filenames = glob.glob(CONFIG_DIR+'*.json')
	print('Reading:')
	for filename in filenames:
		print(f'    "{filename}"')
		with open(filename,"r") as json_data:
			d = json.load(json_data)
			for stream in d:
				STREAMS.append(stream['url'])
	LEN_STREAMS = len(STREAMS)
	print(f"Red: {LEN_STREAMS} stream url's")
	
def pick_a_stream():
	global STREAMS,LEN_STREAMS,YOUTUBE_IS_NICE
	while True:
		stream = STREAMS[random.randint(1,LEN_STREAMS)-1]
		if YOUTUBE_IS_NICE:
			return stream
		if not 'youtu' in stream:
			return stream
	
class StreamDisplayer:
	def __init__(S,url,patients_secs=5):
		print(f'StreamDisplayer("{url}")')
		global XSCREENSAVER_WINDOW,YOUTUBE_IS_NICE
		S.url=url
		S.running=False
		S.poll = None
		S.mpv_options = ["mpv"]
		if XSCREENSAVER_WINDOW:
			print(f'{XSCREENSAVER_WINDOW=}')
			S.mpv_options += ["-no-audio","-really-quiet","--fullscreen","-no-stop-screensaver"]
			S.mpv_options += ['--wid='+str(XSCREENSAVER_WINDOW)]
			S.screen_mode_options()
		else:
			pass
			# S.screen_mode_options()
			# S.mpv_options.append('--fullscreen')
		S.cookies_chooser()
		S.mpv_options+=[S.url]
		print (f'{S.mpv_options=}')
		
		S.mpv_proc = subprocess.Popen(S.mpv_options,stdout=subprocess.PIPE,stderr=subprocess.DEVNULL,text=True)
		sleep(patients_secs)
		if S.mpv_proc.poll():
			print(f'StreamDisplayer FAILED')
			if 'youtu' in S.url:
				YOUTUBE_IS_NICE = False
			raise RuntimeError
			
		S.running=True
		
	def screen_mode_options(S):
		if args.mode:
			if args.mode == 'original':
				return
			if args.mode == 'stretch':
				S.mpv_options += ["--keepaspect=no"]
				return
			if args.mode == 'zoom':
				S.mpv_options += ["--video-zoom=1","--panscan=1.0"]
				return
			S.mpv_options += ["--keepaspect=no"]
		
	def is_running(S):
		S.poll = S.mpv_proc.poll()
		#print(f'{S.poll=}')
		if S.poll:
			S.running = False
			return False
		S.running = psutil.pid_exists(S.mpv_proc.pid)
		return S.running
	
	def terminate(S):
		if S.running:
			S.mpv_proc.terminate()
		S.running = False
	
	def kill(S):
		if S.running:
			S.mpv_proc.kill()
		S.running = False
	
	def cookies_chooser(S):
		global COOKIES_FILE,BROWSERS
		for browser in BROWSERS:
			if is_process_running(browser):
				S.mpv_options += [f"--ytdl-raw-options=cookies-from-browser={browser}"]
				return
		if os.path.isfile(COOKIES_FILE):
			S.mpv_options += [f"--ytdl-raw-options=cookies={COOKIES_FILE}"]
			
def is_process_running(process_name):
	"""
	Check if there is any running process that contains the given name.
	"""
	for proc in psutil.process_iter(['name']):
		try:
			# Check if process name contains the given name string
			if process_name.lower() in proc.info['name'].lower():
				return True
		except (psutil.NoSuchProcess, psutil.AccessDenied, psutil.ZombieProcess):
			pass
	return False

def main():
	global ACTIVE_STREAM,XSCREENSAVER_WINDOW,SHOW_TIME_SECS
	print (sys.argv)
	
	if args.show_time:
		SHOW_TIME_SECS=args.show_time
		print(f'{SHOW_TIME_SECS=}')
	
	read_streams()
	
	while True:
		stream_url = pick_a_stream()
		try:
			ACTIVE_STREAM = StreamDisplayer(stream_url)
		except RuntimeError:
			if ACTIVE_STREAM:
				ACTIVE_STREAM.kill()
			continue
		end_of_show_time=time.time() + SHOW_TIME_SECS
		count_down=SHOW_TIME_SECS
		sleep_time = 3
		#print(f'{SHOW_TIME_SECS} seconds loop started:\n')
		while (time.time() < end_of_show_time) and ACTIVE_STREAM.is_running():
			sleep(sleep_time)
			count_down -= sleep_time
			#print(f'{count_down:03} runing {ACTIVE_STREAM.is_running()}',flush=True)
		ACTIVE_STREAM.terminate()
		
if __name__ == '__main__':
	try:
		main()
	except KeyboardInterrupt:
		print("\nScreensaver halted.")
		sys.exit(0)
		
